name: optic_calc_mobile
description: OptiCalc Mobile - real-time optical polarization simulation tool.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
